GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQzMjA0Mjg2fQ.HjTb26ip-65kASqJ114uLNNne8YmLkLId3PsixaEhPc

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Jim"
}